import Navigation from "../components/navigation";
import { Metadata } from "next";
import "../styles/global.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Next JS 14",
    default: "Next JS 14",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
